- docker/udev/10-mars-rover.rules
- rover_ws/src/rover_control/config/teleop_twist.yaml
- rover_ws/src/rover_control/launch/mobility.launch.py
- rover_ws/src/rover_control/rover_control/mega_wrapper.py
- rover_ws/src/rover_control/setup.py
- zed_ws/src/ZED_ROS2_Wrapper_nogit/docker/Dockerfile
- zed_ws/src/ZED_ROS2_Wrapper_nogit/docker/docker-compose.yaml
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/CMakeLists.txt
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/LICENSE
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/include/cuda_utils.h
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/include/logging.h
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/include/utils.h
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/include/yolo.hpp
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/launch/object_detection_launch.py
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/package.xml
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/params/config.yaml
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/src/main.cpp
- zed_ws/src/ZED_ROS2_Wrapper_nogit/object_detection/src/yolo.cpp
Add a brief summary of the changes you made here:
...
> Mega update

- docker/udev/10-mars-rover.rules
- docker/udev/create_udev_rule.sh
- rover_ws/src/unilidar_sdk/unitree_lidar_ros2/src/unitree_lidar_ros2/launch/launch.py
Add a brief summary of the changes you made here:
...
> wip on the udev creator script

- zed_ws/docker/AMD_Desktop/Dockerfile
- zed_ws/docker/AMD_Desktop/docker-compose.yaml
- zed_ws/src/zed-ros2-wrapper/zed_wrapper/config/common_stereo.yaml
Add a brief description of the changes in this pull request:
...
> Docker amd

- docker/Dockerfile
- scripts/simulation/mcp_server.py
> Added MCP server for a natural language interface

- .gitignore
- README.md
- base_scripts/tools/mcp_agent.sh
- scripts/simulation/mcp_server.py
> Adding MCP image support

- base_scripts/tools/mcp_agent.sh
> Quick MCP agent demo update

- docker/Dockerfile
> Quick Dockerfile fix

- docker/Dockerfile
> Added dependency for MCP images

- rover_ws/src/rover_gui/rover_gui/autonomy_gui.py
- rover_ws/src/rover_interfaces/CMakeLists.txt
- rover_ws/src/rover_interfaces/srv/AddWaypoint.srv
- rover_ws/src/rover_interfaces/srv/GetFeedback.srv
- rover_ws/src/rover_interfaces/srv/GetWaypoints.srv
- rover_ws/src/rover_interfaces/srv/IsTaskRunning.srv
- rover_ws/src/rover_interfaces/srv/RemoveWaypoint.srv
- rover_ws/src/rover_interfaces/srv/SendWaypoint.srv
- scripts/precache_tiles.py
- scripts/simulation/mcp_server.py
> Improved MCP GUI Integration

- GEMINI.md
- README.md
> Adding MCP how-to video, LLM instructional file

- GEMINI.md
> Added GitHub help to GEMINI.md

- docker/Dockerfile
> Testing GTSAM Docker build

- docker/Dockerfile
> Final Docker fix

- docker/Dockerfile
> Docker fix

- docker/Dockerfile
> Last Docker fix

- docker/Dockerfile
> Quick Docker fix

- README.md
- scripts/simulation/mcp_server.py
> Final quick fixes for 2026 team

- README.md
- scripts/linux_write_patch.sh
> Fixed naming inconsistency

- compose.sh
> Quick patch for GUI displays on setup

- docker/docker-compose.yaml
> Quick fix for build context (as found with the Science team)
